### ISSUE TITLE
Utilizando sequelize models e migration

### ISSUE THREAD

**Issue by renanmoraes** [talesluna/base-nodejs-api-es6#1]
Bom amei sua API, porém estou tendo dificuldades em utiliza-la com models e  migrations, vi e entendi sua logica de pegar as models porém não encontrei nada falando sobre o migrations.

Como faço para utilizar squelize migrate (por exemplo) em sua api ?

Se não tiver como usar migration, poderia dar um exemplo de como utlizar o model nas rotas, pois não está funcionando como esperado. Ja tentei importar, requerir e criar variavel para o model porém ele nunca encontra.

**Comment by talesluna** [comment]
@renanmoraes agradeço seu feedback

As migrations com Sequelize podem ser feitas através do **sequelize-cli** ([ver documentação](http://docs.sequelizejs.com/manual/tutorial/migrations.html)) e no momento não há nenhuma integração deste com a API, porém nas versões mais atuais o Sequelize [implementou o suporte a alterações de tabelas durante a sincronização dos modelos (.sync())](https://github.com/sequelize/sequelize/issues/537). Para que essas alterações ocorram durante a sincronização é nescessário informar **{alt: true}** nos parâmetros do metódo .sync() o que no momento não está implementado, irei implementar nas configurações dos bancos de dados em *.env.js a opção de definir se a api deve ou não realizar as tentativas de alter table.

**Note:** 

A opção **{force: true}** presente no metódo sync() durante o desenvolvimento deleta todas as tabelas e refaz a sincronização "inicial", já a opção **{alter: true}** foi requisitada pelos usuários e implementada para o ambiente de produção contudo ainda é preferencial que em produção se use o migrate do sequelize-cli para eventuais alterações, por questões da integridade das informações.

As alterações podem falhar se o SGBD conseguir detectar conflitos de integridade foreign keys ou tipos incompátiveis de dados na coluna por exemplo.

**Comment by renanmoraes** [comment]
Obrigado pelo excelente trabalho !
