### ISSUE TITLE
Rota com slect, limit, e where

### ISSUE THREAD

**Issue by renanmoraes** [talesluna/base-nodejs-api-es6#2]
Poderia demonstrar um exemplo de como deve ser feito a requisição para a Api, que contenha select, limit e where ?

Sei que consigo passar, mais como deve ser enviado. Pela própria url, pelo body ?

Obrigado mais uma vez.

**Comment by talesluna** [comment]
Esses parâmetros podem ser informados através de query string na URL requisitada

**limit** recebe um valor em inteiro, **select** recebe um ou mais valores separados por vírgula, e **where** recebe a representação de um objeto JSON

#### Exemplo:
/my/route?limit=20&select=field1,field2&where={a: 1, b:2}

**Comment by renanmoraes** [comment]
Top vlw brother !
