### ISSUE TITLE
Exemplo de melhor utilização de uma middleware utilizando a api

### ISSUE THREAD

**Issue by renanmoraes** [talesluna/base-nodejs-api-es6#3]
Poderia disponibilizar um exemplo de implementação de uma middleware em sua API ?

Obrigado até o momento.

**Comment by talesluna** [comment]
A middlewares seguem o padrão do ExpressJS
**Documentação**: http://expressjs.com/pt-br/guide/using-middleware.html

Você deve criar suas rotas, express middlewares e validators em src/api/you_rest_module
**Exemplo**: https://github.com/talesluna/base-nodejs-api-es6/tree/master/src/api/example
