### ISSUE TITLE
[PEDIDO] Inclusão de paginação

### ISSUE THREAD

**Issue by renanmoraes** [talesluna/base-nodejs-api-es6#4]
Bom seria muito interessante se tivesse alguma forma de implementar em sua api a paginação.

Seria da seguinte forma:

Tenho 300 registros, na primeira requisição eu traria apenas X = 10, então a api iria me retornar, os registros e um links para próximas paginas e anteriores.

@talesluna  teria como implementar algo assim :?

**Comment by talesluna** [comment]
A paginação hoje existe de forma clássica, você pode usar **_limit_** e **_offset_** para fazer paginação simples, porém a API não fornece a contagem de registros a serem paginados nem a página atual ou navegação por número da página, essa feature será implementada em breve assim que possível.

Exemplo da paginação atual:
/your/endpoint/?limit=10&offset=20

Retorna 10 registros a começar do 20º
