### ISSUE TITLE
[TIPS] validation fails return code

### ISSUE THREAD

**Issue by Wanber** [talesluna/base-nodejs-api-es6#8]
Consider use 422 (UNPROCESSABLE_ENTITY) for validade errors, rather than 500.

**Comment by talesluna** [comment]
Improved at https://github.com/talesluna/base-nodejs-api-es6/commit/1a5ac5b134d91a414c3d1672a33c8c7d50347229#diff-f1ae5ebfdbb86d8cab5b67ce45403263R18
