### ISSUE TITLE
[TIPS] promises lint

### ISSUE THREAD

**Issue by Wanber** [talesluna/base-nodejs-api-es6#9]
Consider use this plugin for lint promises

`$ npm install eslint-plugin-promise --save-dev`

> .eslintrc

```javascript
{
  "plugins": ["promise"],
  "extends": ["plugin:promise/recommended"],
  "rules": {
        "promise/avoid-new": "off",
}
```

https://github.com/xjamundx/eslint-plugin-promise

**Comment by talesluna** [comment]
Implemented at: https://github.com/talesluna/base-nodejs-api-es6/commit/1a5ac5b134d91a414c3d1672a33c8c7d50347229#diff-e4403a877d80de653400d88d85e4801aR6
